version: "3.9"

services:
  web:
    build:
      context: ./backend      # ← контекст — папка backend
      dockerfile: Dockerfile  # ← Dockerfile внутри папки backend
    working_dir: /code
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/code
      - DJANGO_SETTINGS_MODULE=settings
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
